<html>
    <head>
    <title>Three Guys - Product</title>
    <link rel="stylesheet" href="../../bootstrap4/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../css/loginc.css" class="css">
    <link rel="stylesheet" href="../../css/style.css" class="css">
    </head>
    <body>
   

      <div class="container">
      <div class="shadow-lg bg-white rounded testmarg">
      <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="POST" enctype="multipart/form-data">
      <div class="text-center">
      <h2>Add Product</h2><br>
          </div>
            <div class="form-group">
            <label for="name"> Name </label>
            <input type="text" name="name" placeholder="product name" class="form-control" required> 
            </div>

            <div class="form-group">
            <label for="price"> Price </label>
            <input type="number" name="price" placeholder="Product Price"  id="price" class="form-control" required>
            <span class="text-danger"><?php if (isset($price_error)) echo $price_error; ?></span>  
            </div>

            <div class="form-group">
                <label class="form-label-group" for="desc"> Description </label>
                <textarea name="desc" id="desc" class="form-control" placeholder="Description" rows="5"></textarea>
                <span class="text-danger"><?php if (isset($desc_error)) echo $desc_error; ?></span>
            </div>
            <div class="form-group">
                <label class="form-label-group" for="type"> Type </label>
                <select name="type" class="form-control" required>
                    <option value="none" default> Choose Type </option>
                    <option value="breakfast"> Weaving </option>
                    <option value="lunch"> Wood Carving </option>
                </select>
                <span class="text-danger"><?php if (isset($type_error)) echo $type_error; ?></span>
            </div>
    
            <div class="form-group">
                <input type="file" class="form-controle" name="pic">
            </div>
            <span class="text-danger"><?php if (isset($file_error)) echo $file_error; ?></span>

       <div class="d-flex justify-content-between mt-3">
    <button type="submit" name="submit" class="btn btn-primary btn-shadow btn-lg">Submit</button>
    <a href="index.php" class="btn btn-secondary btn-shadow btn-lg">Back</a>
</div>
            </form>
      </div>
      </div>
      <script src="../../bootstrap4/js/bootstrap.min.js"></script>
            </body>
</html>